apiVersion: app.example.com/v1alpha1
kind: GreenScalerService
metadata:
  labels:
    app.kubernetes.io/name: greenscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: greenscalerservice-sample
spec:
  # TODO(user): Add fields here
