apiVersion: app.example.com/v1alpha1
kind: GreenScaler-Service
metadata:
  labels:
    app.kubernetes.io/name: greenscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: greenscaler-service-sample
spec:
  # TODO(user): Add fields here
