apiVersion: app.example.com/v1alpha1
kind: GreenScalerService
metadata:
  labels:
    app.kubernetes.io/name: greenscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: greenscalerservice-sample
spec:
  timeZone: "UTC"
  targets:
    - kind: Deployment
      name: my-app
      namespace: default
  schedule:
    - from: "09:00"
      to: "18:00"
      replicas: 3
    - from: "18:00"
      to: "09:00"
      replicas: 0
